### ISSUE TITLE
Import excel/csv tidak bisa

### ISSUE THREAD

**Issue by yo5ep** [manh21/eVoting#10]
Maaf izin laporan mas, di saya ada error import Excel/csv

A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /home/smrmldhv/public_html/evoting/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx.php:1332)

Filename: core/Common.php

Line Number: 570

Backtrace:

**Comment by yo5ep** [comment]
sementara saya import csv langsung dr phpmyadmin.. :)

**Comment by manh21** [comment]
Gunakan versi PHP 7.3 atau yang baru
