### ISSUE TITLE
Cara ganti Frontpage

### ISSUE THREAD

**Issue by saklarlampu** [manh21/eVoting#11]
maaf mas naufal, saya menggunakan aplikasi buatan mas. untuk mengganti frontpage nya dari tulisan SMANSA bagaimana ya? saya masih awam dengan PHP,Codeigniter. Terimakasih

**Comment by manh21** [comment]
Silahkan merubah file `main.php` yang ada di dalam folder `/application/views/front/` https://github.com/manh21/eVoting/blob/master/application/views/front/main.php
