### ISSUE TITLE
error di hosting saat login admin

### ISSUE THREAD

**Issue by saklarlampu** [manh21/eVoting#12]
pada saat di XAMPP udah lancar bisa login,dll

![Capture](https://user-images.githubusercontent.com/72787562/109749497-5eb0db80-7c0d-11eb-9a36-d99d13e2896e.PNG)

tapi ketika di test di 000webhost
saat login admin dapat error  seperti di screenshot
terimakasih mas naufal sebelumnya.

**Comment by manh21** [comment]
Pengaruh hostingnya itu. 
Referensi https://sekolahkoding.com/forum/lancar-di-localhost-error-saat-hosting-1575428046
