### ISSUE TITLE
Error setelah login dan akan memvoting

### ISSUE THREAD

**Issue by NatsukiKanata** [manh21/eVoting#19]
**Description**
Muncul error setelah login dan akan memvoting

**To reproduce**
1. Buka https://pemilos.smpn2ngaglik.my.id
2. Login dengan username dan password 50505
3. Lalu error

**Screenshots**
![Screenshot_20221030-213524_Chrome](https://user-images.githubusercontent.com/80439646/198884752-9795b7e0-2713-4f58-9b84-4a0bcc2ba98a.png)

**Additional context**
Server: Ubuntu 22.04
PHP: 7.4.32
MariaDB: 10.6.7-MariaDB-2ubuntu1.1

**Comment by NatsukiKanata** [comment]
Hasil `var_dump($settings)`
![Screenshot_20221030-215414_Chrome](https://user-images.githubusercontent.com/80439646/198886028-c81e8f7a-f18a-4954-b0c9-62883401f0b5.png)

**Comment by NatsukiKanata** [comment]
Apakah tidak support di Ubuntu Server?

**Comment by manh21** [comment]
Support server ubuntu
