### ISSUE TITLE
Tidak bisa menambahkan kandidat

### ISSUE THREAD

**Issue by NatsukiKanata** [manh21/eVoting#22]
**Describe the bug**
Tidak bisa menambahkan kandidat

**Records**
https://user-images.githubusercontent.com/80439646/199537653-a91a8876-12af-461b-a226-6b5c2d7105f6.mp4

**Additional context**
Server: Ubuntu 22.04
PHP: 7.4.32
MariaDB: 10.6.7-MariaDB-2ubuntu1.1

**Comment by NatsukiKanata** [comment]
Apakah ada solusi @manh21

**Comment by manh21** [comment]
extension gambar yang digunakan untuk upload `jpeg`, sedangkan yang di perbolehkan hanya `.jpg` atau `.png`.

solusinya silahkan convert gambar terlebih dahulu ke format yang di perbolehkan
