### ISSUE TITLE
Waktu Login User malah Error database

### ISSUE THREAD

**Issue by abiey22** [manh21/eVoting#23]
Mohon solusinya mas...agar bisa lancar ketika nanti dipakai
![login](https://user-images.githubusercontent.com/50065928/199888362-ba5a45f6-4ced-48f9-9784-6ecc93554eae.png)

**Comment by manh21** [comment]
sebelumnya mungkin bisa diberi tahu, versi PHP yang di gunakan

**Comment by manh21** [comment]
Silahkan coba download kembali code yang baru, jika  masih terdapat kendala bisa membuka kembali issues ini
