### ISSUE TITLE
404 pada localhost/evoting/user

### ISSUE THREAD

**Issue by ghulamikhsan** [manh21/eVoting#4]
404 pada bagian user setelah login? udah cek semua syntax kayaknya bener cuman sekarang belum ketemu errornya apa 
![image](https://user-images.githubusercontent.com/37178831/69042600-0f4c9900-0a24-11ea-90ae-7c79f70b59b6.png)

**Comment by manh21** [comment]
coba ketik ini di url nya localhost/user

**Comment by manh21** [comment]
Solusi permasalahn ini adalah dengan merestart apache dan mysql

**Comment by dzakiabd** [comment]
saat mengklik login di localhost/evoting malah dialihkan ke localhost/dashboard/ . itu kenapa ya?

**Comment by yo5ep** [comment]
Maaf mas Naufal saya izin memakai aplikasinya di hosting,, permasalahanya ketika source code di jalankan di http://localhost/evoting/user berjalan normal.
tetapi ketika saya upload ke hosting, setelah setting2 db semua beres.. saya gunakan evoting.domainsaya.com/user terjadi 404 Page Not Found. untuk evoting.domainsaya.com/admin tidak ada masalah
mohon solusinya. 
terimakasih.
