### ISSUE TITLE
Reset sudah memilih menjadi belum memilih

### ISSUE THREAD

**Issue by cucurkeju** [manh21/eVoting#7]
ndan ketika data anak yang sudah memilih saya klik jadi belum memilih, memang sih anak itu jadi bisa memilih lagi, namun masalahnya terdapat di data suara masuk tidak otomatis tercancel,

tolong supaya dibenerin jadi ketika ada anak yang aslinya belum memilih tapi disana tertulis sudah memilih, dan ketika di reset anak itu kalo bisa pada hasil suara masuk juga di hilangkan untuk pilihan dari anak tersebut, mungkin cuman itu aja,, thanks

**Comment by manh21** [comment]
> tolong supaya dibenerin jadi ketika ada anak yang aslinya belum memilih tapi disana tertulis sudah memilih

 karena usernamenya double/ganda jadi bisa kayak gitu
