### ISSUE TITLE
evoting.domainsaya.com/user terjadi 404 Page Not Found

### ISSUE THREAD

**Issue by yo5ep** [manh21/eVoting#9]
Maaf mas Naufal saya izin memakai aplikasinya di hosting,, permasalahanya ketika source code di jalankan di http://localhost/evoting/user berjalan normal.
tetapi ketika saya upload ke hosting, setelah setting2 db semua beres.. saya gunakan evoting.domainsaya.com/user terjadi 404 Page Not Found. untuk evoting.domainsaya.com/admin tidak ada masalah
mohon solusinya.
terimakasih.

**Comment by manh21** [comment]
Silahkan untuk di hosting. Kalo pakek `evoting.domainsaya.com/user/userauth` 404 atau tidak mas? soalnya diserver `evoting.domainsaya.com/user` saya dapat diakses tanpa kendala.

**Comment by yo5ep** [comment]
Sama mas 404,, 
Itu yg di readme utk setting user autentifikasi, token, key, dll sy belum di sesuaikan. Mksdnya itu bgmn mas?

**Comment by yo5ep** [comment]
Mf baru belajar..
Yg API Default Settings:

**Comment by manh21** [comment]
> Itu yg di readme utk setting user autentifikasi, token, key, dll sy belum di sesuaikan. Mksdnya itu bgmn mas?
Disetting kalo mau buat aplikasi sendiri mas cthnya: evoting android nanti komunikasi server pakek api itu.
Tidak perlu diseeting bila tidak digunakan

**Comment by yo5ep** [comment]
Ok.
Lalu kira² errornya dari apa ya?

**Comment by manh21** [comment]
Sepertinya perlu index.php coba `evoting.domainsaya.com/index.php/user` apakah 404?

**Comment by yo5ep** [comment]
Masih 404..

**Comment by manh21** [comment]
hmm sungguh aneh. [https://test.manh21.com/](https://test.manh21.com/) baru saja saya upload ke test server tapi berjalan tanpa kendala.

**Comment by yo5ep** [comment]
ko tampilanya home sedikit berbeda dg di saya mas, kalo sy fontnya kecil² tdk terlalu responsive

**Comment by manh21** [comment]
Tampilan yang seharusnya seperti yang di [https://test.manh21.com/](https://test.manh21.com/). Tampilan bisa beda karena 2 hal kesalahn konfigurasi server atau kesalahan pada saat instalasi

**Comment by yo5ep** [comment]
Source sy download dr blog, bukan dr github.

**Comment by manh21** [comment]
Source yang terupdate ada digithub mas.

**Comment by manh21** [comment]
Silahkan download lagi digithub

**Comment by yo5ep** [comment]
Oke mas sdh upload ulang download dr GitHub, sudah work sama tampilanya responsive di android...👍

Terimakasih🙏

**Comment by yo5ep** [comment]
Blog yg sy maksud ini https://csgwebku.blogspot.com/2020/12/download-source-code-aplikasi-pemilihan.html

**Comment by yo5ep** [comment]
Terimakasih🙏
